### ISSUE TITLE
ZINC and molhiv different preprocessing

### ISSUE THREAD

**Issue by sooheon** [DevinKreuzer/SAN#1]
On master MolHIVDataset and MoleculeDataset (for ZINC) have different eigvec preprocessing, the latter does not normalize the eigvectors. Was the zinc task mae achieved without this normalization?

Thanks for the code and great ideas.

**Comment by sooheon** [comment]
Additionally molhiv uses the symmetric laplacian, and zinc uses just L = D - A.

**Comment by DevinKreuzer** [comment]
Thank you so much for noticing this. I was experimenting with these changes at the last second and forgot to put them back.

Using the symmetric or normal Laplacian (L=D-A) actually produces the same results! The normalization is actually a normalization over the rows of L (not columns) which turns out to also have a negligible effect. I may remove this line eventually.

Best,
Devin

**Comment by sooheon** [comment]
Thanks for clarifying. Is your interpretation that the laplace etiquettes re: normalization are not relevant for the task, or that the lpe transformer performs the normalization (via it's internal layernorm?)

**Comment by DevinKreuzer** [comment]
The eigenvector normalization is automatically done when we compute the eigenvectors with `np.linalg.eig()`. The normalization you are mentioning is a normalization over the rows of the Laplacian (it's a different normalization).

In an earlier version of our model, it produced major benefits. My intuition is it made the input embedding more invariant to the number of nodes in the graph. With the final SAN model we proposed, it had minimal effect, and we didn't discuss it much in the paper. As I mentioned, I am considering removing this line eventually as it has no substantial effect.

All the best,
Devin

**Comment by sooheon** [comment]
Gotcha, thanks
